updated buildlinuximage.sh

diff --git a/src/platform/unix/BuildLinuxImage.sh.in b/src/platform/unix/BuildLinuxImage.sh.in
--- a/src/platform/unix/BuildLinuxImage.sh.in
+++ b/src/platform/unix/BuildLinuxImage.sh.in
@@ -1,126 +1,122 @@
 #!/bin/bash
+set -e
 
-#
-# This script can download and compile dependencies, compile SuperSlicer
-# and optional build a .tgz and an appimage.
-#
-# Original script from SuperSlicer by supermerill https://github.com/supermerill/SuperSlicer
-#
-# Change log:
-#
-# 20 Nov 2023, wschadow, branding and minor changes
-# 01 Jan 2024, wschadow, added build options
-#
-
-# Our sysctl call may be run as normal user,
-# but /sbin is not always in normal users' PATH.
+# Add /sbin to path if necessary
 if [[ -f /sbin/sysctl && -x /sbin/sysctl ]]; then sysctl_bin=/sbin/sysctl
-else sysctl_bin=sysctl  # If not found in sbin, hope
+else sysctl_bin=sysctl
 fi
 
-export ROOT=`pwd`
-export NCORES=`nproc`
+export ROOT=$(pwd)/build
+mkdir -p "$ROOT"
+echo "ROOT is set to: $ROOT"
+
+export NCORES=$(nproc)
 
 VERSION_NUMBER=""
+GTK_VERSION=""
+BUILD_APP=""
+BUILD_IMAGE=""
+
 while getopts ":iagvhg:" opt; do
   case ${opt} in
     i )
-        export BUILD_IMAGE="1"
+        BUILD_IMAGE="1"
         ;;
     a )
-        export BUILD_APP="1"
+        BUILD_APP="1"
         ;;
     g )
         GTK_VERSION=$OPTARG
         ;;
     v )
-        export VERSION_NUMBER="-@SLIC3R_VERSION_FULL@"
+        VERSION_NUMBER="-@SLIC3R_VERSION_FULL@"
         ;;
-    h ) echo "Usage: ./BuildLinuxImage.sh [-g][-i][-a][-h]"
-        echo "   -g: force gtk2 build"
+    h )
+        echo "Usage: ./BuildLinuxImage.sh [-g GTK_VERSION][-i][-a][-v][-h]"
+        echo "   -g: force gtk2 or gtk3 build"
         echo "   -i: generate .tgz and Appimage (optional)"
-        echo "   -a: generate app (optional)"
-        echo "   -v: with version number (optional)"
+        echo "   -a: generate app only (optional)"
+        echo "   -v: add version number (optional)"
         echo "   -h: help"
         exit 0
+        ;;
+    \? )
+        echo "Invalid Option: -$OPTARG" 1>&2
+        exit 1
         ;;
   esac
 done
 
-if [[ -n "$BUILD_APP" ]]
-then
+if [[ -n "$BUILD_APP" ]]; then
     echo -e "\n[7/8] Generating Linux app ..."
-    # create directory and copy into it
-    if [ -d "package" ]
-    then
+
+    if [[ -d "package" ]]; then
         rm -rf package/*
-        rm -rf package/.* 2&>/dev/null
+        find package -mindepth 1 -delete
     else
         mkdir package
     fi
-    mkdir package/bin
+    mkdir -p package/bin
 
-    # copy Resources
     cp -rf ../resources/ package/resources
     cp -f bin/@SLIC3R_APP_CMD@ package/bin/@SLIC3R_APP_CMD@
-    cp -f src/OCCTWrapper.so package/bin    
+    cp -f src/OCCTWrapper.so package/bin
+
     ln -rs package/bin/@SLIC3R_APP_CMD@ package/bin/@GCODEVIEWER_APP_CMD@
-    # remove unneeded po from resources
-    find package/resources/localization -name "*.po" -type f -delete
-    find package/resources/localization -name "*.pot" -type f -delete
-    find package/resources/localization -name "*.ini" -type f -delete
-    find package/resources/localization -name "*.py" -type f -delete
-    find package/resources/localization -name "*.md" -type f -delete
-    find package/resources/localization -name "*.txt" -type f -delete
-    find package/resources/localization -name "*database*" -type f -delete
-    find package/resources/localization -name "Slic3r.mo" -type f -delete
 
-    # copy occtwrapper
-    cp src/OCCTWrapper.so package/bin/OCCTWrapper.so
+    find package/resources/localization \( -name "*.po" -o -name "*.pot" -o -name "*.ini" -o -name "*.py" -o -name "*.md" -o -name "*.txt" -o -name "*database*" -o -name "Slic3r.mo" \) -type f -delete
 
-    # create bin
     echo -e '#!/bin/bash\nDIR=$(readlink -f "$0" | xargs dirname)\nexport LD_LIBRARY_PATH="$DIR/bin"\nexec "$DIR/bin/@SLIC3R_APP_CMD@" "$@"' > package/@SLIC3R_APP_CMD@
-    chmod ug+x package/@SLIC3R_APP_CMD@
+    chmod +x package/@SLIC3R_APP_CMD@
+
     echo -e '#!/bin/bash\nDIR=$(readlink -f "$0" | xargs dirname)\nexport LD_LIBRARY_PATH="$DIR/bin"\nexec "$DIR/bin/@GCODEVIEWER_APP_CMD@" "$@"' > package/@GCODEVIEWER_APP_CMD@
-    chmod ug+x package/@GCODEVIEWER_APP_CMD@
-    echo -e "\n... done\n"
+    chmod +x package/@GCODEVIEWER_APP_CMD@
+
+    echo -e "\n... app package prepared\n"
 fi
 
-if [[ -n "$BUILD_IMAGE" ]]
-then
-    echo -e "\n[8/8] Creating .tgz and Appimage for distribution ...\n"
+if [[ -n "$BUILD_IMAGE" ]]; then
+    echo -e "\n[8/8] Creating .tgz and AppImage for distribution ..."
 
     pushd package > /dev/null
-    if [[ "$GTK_VERSION" == 2 ]]
-    then
-       tar -czvf ../@SLIC3R_APP_KEY@${VERSION_NUMBER}-linux-x64-GTK2.tgz . &>/dev/null
-    elif [[ "$GTK_VERSION" == 3 ]]
-    then
-       tar -czvf ../@SLIC3R_APP_KEY@${VERSION_NUMBER}-linux-x64-GTK3.tgz . &>/dev/null
+    if [[ "$GTK_VERSION" == 2 ]]; then
+        tar -czvf ../@SLIC3R_APP_KEY@${VERSION_NUMBER}-linux-x64-GTK2.tgz . > /dev/null
+    elif [[ "$GTK_VERSION" == 3 ]]; then
+        tar -czvf ../@SLIC3R_APP_KEY@${VERSION_NUMBER}-linux-x64-GTK3.tgz . > /dev/null
     else
-        echo -e "\nError, only GTK2 and GTK3 version are supported. Asked GTK version: '$GTK_VERSION'\n"
+        echo -e "\nError: Only GTK2 and GTK3 versions are supported. Asked GTK version: '$GTK_VERSION'"
+        exit 1
     fi
     popd > /dev/null
 fi
 
-    echo "> ls package/.."
-    ls -al ..
-    echo "> ls package/../src"
-    ls -al ../src
-    echo "> ls -al ROOT(build)/bin"
-    ls -al $ROOT/bin
-    echo "> ls -al ROOT(build)/src"
-    ls -al $ROOT/src
-    chmod +x ../src/build_appimage.sh
-    ../src/build_appimage.sh
-    popd  > /dev/null
-    if [[ "$GTK_VERSION" == 2 ]]
-    then
-        mv package/"@SLIC3R_APP_KEY@_ubu64.AppImage" "@SLIC3R_APP_KEY@${VERSION_NUMBER}-linux-x64-GTK2.AppImage"
-    elif [[ "$GTK_VERSION" == 3 ]]
-        mv package/"@SLIC3R_APP_KEY@_ubu64.AppImage" "@SLIC3R_APP_KEY@${VERSION_NUMBER}-linux-x64-GTK3.AppImage"
-    else
-        echo -e "\nError, onl GTK2 and GTK3 verison are supported. Asked GTK version: 
-    fi
-    echo -e "\n... done\n"
+# Build AppImage
+chmod +x ../src/build_appimage.sh
+../src/build_appimage.sh
+
+# Show content
+if [[ -d "$ROOT/bin" ]]; then
+    echo "> ls -al $ROOT/bin"
+    ls -al "$ROOT/bin"
+else
+    echo "Warning: $ROOT/bin does not exist"
 fi
+
+if [[ -d "$ROOT/src" ]]; then
+    echo "> ls -al $ROOT/src"
+    ls -al "$ROOT/src"
+else
+    echo "Warning: $ROOT/src does not exist"
+fi
+
+# Rename AppImage after build
+if [[ "$GTK_VERSION" == 2 ]]; then
+    mv package/"@SLIC3R_APP_KEY@_ubu64.AppImage" "@SLIC3R_APP_KEY@${VERSION_NUMBER}-linux-x64-GTK2.AppImage"
+elif [[ "$GTK_VERSION" == 3 ]]; then
+    mv package/"@SLIC3R_APP_KEY@_ubu64.AppImage" "@SLIC3R_APP_KEY@${VERSION_NUMBER}-linux-x64-GTK3.AppImage"
+else
+    echo -e "\nError: Only GTK2 and GTK3 versions supported. Asked GTK version: '$GTK_VERSION'"
+    exit 1
+fi
+
+echo -e "\n... done\n"
